<?php
/**
* Joomcck by joomcoder
* a component for Joomla 4 CMS (http://www.joomla.org)
* Author Website: https://www.joomcoder.com/
* @copyright Copyright (C) 2020 joomcoder (https://www.joomcoder.com). All rights reserved.
* @license   GNU/GPL http://www.gnu.org/copyleft/gpl.html
*/

namespace Joomcck\Layout\Helpers;


use Joomla\CMS\Layout\LayoutHelper;

defined('_JEXEC') or die();

Class Layout extends LayoutHelper {



	public static function render($layoutFile, $displayData = null, $basePath = '', $options = null)
	{

		// if null options make sure joomcck frontend used
		if(is_null($options)){

			$options = [
				'site' => 'client',
				'component' => 'com_joomcck'
			];

		}


		return parent::render($layoutFile, $displayData, $basePath, $options); // TODO: Change the autogenerated stub
	}


}