CREATE TABLE IF NOT EXISTS  `#__js_res_field_telephone` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL DEFAULT '',
  `code2` varchar(2) NOT NULL DEFAULT '',
  `code3` varchar(3) NOT NULL DEFAULT '',
  `phone_code` varchar(10) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


DELETE FROM `#__js_res_field_telephone`;

INSERT INTO `#__js_res_field_telephone` VALUES (1,'Afghanistan','AF','AFG','93');
INSERT INTO `#__js_res_field_telephone` VALUES (2,'Albania','AL','ALB','355');
INSERT INTO `#__js_res_field_telephone` VALUES (3,'Algeria','DZ','DZA','213');
INSERT INTO `#__js_res_field_telephone` VALUES (4,'American Samoa','AS','ASM','1-684');
INSERT INTO `#__js_res_field_telephone` VALUES (5,'Andorra','AD','AND','376');
INSERT INTO `#__js_res_field_telephone` VALUES (6,'Angola','AO','AGO','244');
INSERT INTO `#__js_res_field_telephone` VALUES (7,'Anguilla','AI','AIA','1-264');
INSERT INTO `#__js_res_field_telephone` VALUES (8,'Antarctica','AQ','ATA','672');
INSERT INTO `#__js_res_field_telephone` VALUES (9,'Antigua and Barbuda','AG','ATG','1-268');
INSERT INTO `#__js_res_field_telephone` VALUES (10,'Argentina','AR','ARG','54');
INSERT INTO `#__js_res_field_telephone` VALUES (11,'Armenia','AM','ARM','374');
INSERT INTO `#__js_res_field_telephone` VALUES (12,'Aruba','AW','ABW','297');
INSERT INTO `#__js_res_field_telephone` VALUES (13,'Australia','AU','AUS','61');
INSERT INTO `#__js_res_field_telephone` VALUES (14,'Austria','AT','AUT','43');
INSERT INTO `#__js_res_field_telephone` VALUES (15,'Azerbaijan','AZ','AZE','994');
INSERT INTO `#__js_res_field_telephone` VALUES (16,'Bahamas','BS','BHS','1-242');
INSERT INTO `#__js_res_field_telephone` VALUES (17,'Bahrain','BH','BHR','973');
INSERT INTO `#__js_res_field_telephone` VALUES (18,'Bangladesh','BD','BGD','880');
INSERT INTO `#__js_res_field_telephone` VALUES (19,'Barbados','BB','BRB','1-246');
INSERT INTO `#__js_res_field_telephone` VALUES (20,'Belarus','BY','BLR','375');
INSERT INTO `#__js_res_field_telephone` VALUES (21,'Belgium','BE','BEL','32');
INSERT INTO `#__js_res_field_telephone` VALUES (22,'Belize','BZ','BLZ','501');
INSERT INTO `#__js_res_field_telephone` VALUES (23,'Benin','BJ','BEN','229');
INSERT INTO `#__js_res_field_telephone` VALUES (24,'Bermuda','BM','BMU','1-441');
INSERT INTO `#__js_res_field_telephone` VALUES (25,'Bhutan','BT','BTN','975');
INSERT INTO `#__js_res_field_telephone` VALUES (26,'Bolivia','BO','BOL','591');
INSERT INTO `#__js_res_field_telephone` VALUES (27,'Bosnia and Herzegovina','BA','BIH','387');
INSERT INTO `#__js_res_field_telephone` VALUES (28,'Botswana','BW','BWA','267');
INSERT INTO `#__js_res_field_telephone` VALUES (29,'Brazil','BR','BRA','55');
INSERT INTO `#__js_res_field_telephone` VALUES (30,'British Indian Ocean Territory','IO','IOT','');
INSERT INTO `#__js_res_field_telephone` VALUES (31,'British Virgin Islands','VG','VGB','1-284');
INSERT INTO `#__js_res_field_telephone` VALUES (32,'Brunei','BN','BRN','673');
INSERT INTO `#__js_res_field_telephone` VALUES (33,'Bulgaria','BG','BGR','359');
INSERT INTO `#__js_res_field_telephone` VALUES (34,'Burkina Faso','BF','BFA','226');
INSERT INTO `#__js_res_field_telephone` VALUES (35,'Burma (Myanmar)','MM','MMR','95');
INSERT INTO `#__js_res_field_telephone` VALUES (36,'Burundi','BI','BDI','257');
INSERT INTO `#__js_res_field_telephone` VALUES (37,'Cambodia','KH','KHM','855');
INSERT INTO `#__js_res_field_telephone` VALUES (38,'Cameroon','CM','CMR','237');
INSERT INTO `#__js_res_field_telephone` VALUES (39,'Canada','CA','CAN','1');
INSERT INTO `#__js_res_field_telephone` VALUES (40,'Cape Verde','CV','CPV','238');
INSERT INTO `#__js_res_field_telephone` VALUES (41,'Cayman Islands','KY','CYM','1-345');
INSERT INTO `#__js_res_field_telephone` VALUES (42,'Central African Republic','CF','CAF','236');
INSERT INTO `#__js_res_field_telephone` VALUES (43,'Chad','TD','TCD','235');
INSERT INTO `#__js_res_field_telephone` VALUES (44,'Chile','CL','CHL','56');
INSERT INTO `#__js_res_field_telephone` VALUES (45,'China','CN','CHN','86');
INSERT INTO `#__js_res_field_telephone` VALUES (46,'Christmas Island','CX','CXR','61');
INSERT INTO `#__js_res_field_telephone` VALUES (47,'Cocos (Keeling) Islands','CC','CCK','61');
INSERT INTO `#__js_res_field_telephone` VALUES (48,'Colombia','CO','COL','57');
INSERT INTO `#__js_res_field_telephone` VALUES (49,'Comoros','KM','COM','269');
INSERT INTO `#__js_res_field_telephone` VALUES (50,'Cook Islands','CK','COK','682');
INSERT INTO `#__js_res_field_telephone` VALUES (51,'Costa Rica','CR','CRC','506');
INSERT INTO `#__js_res_field_telephone` VALUES (52,'Croatia','HR','HRV','385');
INSERT INTO `#__js_res_field_telephone` VALUES (53,'Cuba','CU','CUB','53');
INSERT INTO `#__js_res_field_telephone` VALUES (54,'Cyprus','CY','CYP','357');
INSERT INTO `#__js_res_field_telephone` VALUES (55,'Czech Republic','CZ','CZE','420');
INSERT INTO `#__js_res_field_telephone` VALUES (56,'Democratic Republic of the Congo','CD','COD','243');
INSERT INTO `#__js_res_field_telephone` VALUES (57,'Denmark','DK','DNK','45');
INSERT INTO `#__js_res_field_telephone` VALUES (58,'Djibouti','DJ','DJI','253');
INSERT INTO `#__js_res_field_telephone` VALUES (59,'Dominica','DM','DMA','1-767');
INSERT INTO `#__js_res_field_telephone` VALUES (60,'Dominican Republic','DO','DOM','1-809');
INSERT INTO `#__js_res_field_telephone` VALUES (61,'Ecuador','EC','ECU','593');
INSERT INTO `#__js_res_field_telephone` VALUES (62,'Egypt','EG','EGY','20');
INSERT INTO `#__js_res_field_telephone` VALUES (63,'El Salvador','SV','SLV','503');
INSERT INTO `#__js_res_field_telephone` VALUES (64,'Equatorial Guinea','GQ','GNQ','240');
INSERT INTO `#__js_res_field_telephone` VALUES (65,'Eritrea','ER','ERI','291');
INSERT INTO `#__js_res_field_telephone` VALUES (66,'Estonia','EE','EST','372');
INSERT INTO `#__js_res_field_telephone` VALUES (67,'Ethiopia','ET','ETH','251');
INSERT INTO `#__js_res_field_telephone` VALUES (68,'Falkland Islands','FK','FLK','500');
INSERT INTO `#__js_res_field_telephone` VALUES (69,'Faroe Islands','FO','FRO','298');
INSERT INTO `#__js_res_field_telephone` VALUES (70,'Fiji','FJ','FJI','679');
INSERT INTO `#__js_res_field_telephone` VALUES (71,'Finland','FI','FIN','358');
INSERT INTO `#__js_res_field_telephone` VALUES (72,'France','FR','FRA','33');
INSERT INTO `#__js_res_field_telephone` VALUES (73,'French Polynesia','PF','PYF','689');
INSERT INTO `#__js_res_field_telephone` VALUES (74,'Gabon','GA','GAB','241');
INSERT INTO `#__js_res_field_telephone` VALUES (75,'Gambia','GM','GMB','220');
INSERT INTO `#__js_res_field_telephone` VALUES (76,'Gaza Strip','','','970');
INSERT INTO `#__js_res_field_telephone` VALUES (77,'Georgia','GE','GEO','995');
INSERT INTO `#__js_res_field_telephone` VALUES (78,'Germany','DE','DEU','49');
INSERT INTO `#__js_res_field_telephone` VALUES (79,'Ghana','GH','GHA','233');
INSERT INTO `#__js_res_field_telephone` VALUES (80,'Gibraltar','GI','GIB','350');
INSERT INTO `#__js_res_field_telephone` VALUES (81,'Greece','GR','GRC','30');
INSERT INTO `#__js_res_field_telephone` VALUES (82,'Greenland','GL','GRL','299');
INSERT INTO `#__js_res_field_telephone` VALUES (83,'Grenada','GD','GRD','1-473');
INSERT INTO `#__js_res_field_telephone` VALUES (84,'Guam','GU','GUM','1-671');
INSERT INTO `#__js_res_field_telephone` VALUES (85,'Guatemala','GT','GTM','502');
INSERT INTO `#__js_res_field_telephone` VALUES (86,'Guinea','GN','GIN','224');
INSERT INTO `#__js_res_field_telephone` VALUES (87,'Guinea-Bissau','GW','GNB','245');
INSERT INTO `#__js_res_field_telephone` VALUES (88,'Guyana','GY','GUY','592');
INSERT INTO `#__js_res_field_telephone` VALUES (89,'Haiti','HT','HTI','509');
INSERT INTO `#__js_res_field_telephone` VALUES (90,'Holy See (Vatican City)','VA','VAT','39');
INSERT INTO `#__js_res_field_telephone` VALUES (91,'Honduras','HN','HND','504');
INSERT INTO `#__js_res_field_telephone` VALUES (92,'Hong Kong','HK','HKG','852');
INSERT INTO `#__js_res_field_telephone` VALUES (93,'Hungary','HU','HUN','36');
INSERT INTO `#__js_res_field_telephone` VALUES (94,'Iceland','IS','IS','354');
INSERT INTO `#__js_res_field_telephone` VALUES (95,'India','IN','IND','91');
INSERT INTO `#__js_res_field_telephone` VALUES (96,'Indonesia','ID','IDN','62');
INSERT INTO `#__js_res_field_telephone` VALUES (97,'Iran','IR','IRN','98');
INSERT INTO `#__js_res_field_telephone` VALUES (98,'Iraq','IQ','IRQ','964');
INSERT INTO `#__js_res_field_telephone` VALUES (99,'Ireland','IE','IRL','353');
INSERT INTO `#__js_res_field_telephone` VALUES (100,'Isle of Man','IM','IMN','44');
INSERT INTO `#__js_res_field_telephone` VALUES (101,'Israel','IL','ISR','972');
INSERT INTO `#__js_res_field_telephone` VALUES (102,'Italy','IT','ITA','39');
INSERT INTO `#__js_res_field_telephone` VALUES (103,'Ivory Coast','CI','CIV','225');
INSERT INTO `#__js_res_field_telephone` VALUES (104,'Jamaica','JM','JAM','1-876');
INSERT INTO `#__js_res_field_telephone` VALUES (105,'Japan','JP','JPN','81');
INSERT INTO `#__js_res_field_telephone` VALUES (106,'Jersey','JE','JEY','');
INSERT INTO `#__js_res_field_telephone` VALUES (107,'Jordan','JO','JOR','962');
INSERT INTO `#__js_res_field_telephone` VALUES (108,'Kazakhstan','KZ','KAZ','7');
INSERT INTO `#__js_res_field_telephone` VALUES (109,'Kenya','KE','KEN','254');
INSERT INTO `#__js_res_field_telephone` VALUES (110,'Kiribati','KI','KIR','686');
INSERT INTO `#__js_res_field_telephone` VALUES (111,'Kosovo','','','381');
INSERT INTO `#__js_res_field_telephone` VALUES (112,'Kuwait','KW','KWT','965');
INSERT INTO `#__js_res_field_telephone` VALUES (113,'Kyrgyzstan','KG','KGZ','996');
INSERT INTO `#__js_res_field_telephone` VALUES (114,'Laos','LA','LAO','856');
INSERT INTO `#__js_res_field_telephone` VALUES (115,'Latvia','LV','LVA','371');
INSERT INTO `#__js_res_field_telephone` VALUES (116,'Lebanon','LB','LBN','961');
INSERT INTO `#__js_res_field_telephone` VALUES (117,'Lesotho','LS','LSO','266');
INSERT INTO `#__js_res_field_telephone` VALUES (118,'Liberia','LR','LBR','231');
INSERT INTO `#__js_res_field_telephone` VALUES (119,'Libya','LY','LBY','218');
INSERT INTO `#__js_res_field_telephone` VALUES (120,'Liechtenstein','LI','LIE','423');
INSERT INTO `#__js_res_field_telephone` VALUES (121,'Lithuania','LT','LTU','370');
INSERT INTO `#__js_res_field_telephone` VALUES (122,'Luxembourg','LU','LUX','352');
INSERT INTO `#__js_res_field_telephone` VALUES (123,'Macau','MO','MAC','853');
INSERT INTO `#__js_res_field_telephone` VALUES (124,'Macedonia','MK','MKD','389');
INSERT INTO `#__js_res_field_telephone` VALUES (125,'Madagascar','MG','MDG','261');
INSERT INTO `#__js_res_field_telephone` VALUES (126,'Malawi','MW','MWI','265');
INSERT INTO `#__js_res_field_telephone` VALUES (127,'Malaysia','MY','MYS','60');
INSERT INTO `#__js_res_field_telephone` VALUES (128,'Maldives','MV','MDV','960');
INSERT INTO `#__js_res_field_telephone` VALUES (129,'Mali','ML','MLI','223');
INSERT INTO `#__js_res_field_telephone` VALUES (130,'Malta','MT','MLT','356');
INSERT INTO `#__js_res_field_telephone` VALUES (131,'Marshall Islands','MH','MHL','692');
INSERT INTO `#__js_res_field_telephone` VALUES (132,'Mauritania','MR','MRT','222');
INSERT INTO `#__js_res_field_telephone` VALUES (133,'Mauritius','MU','MUS','230');
INSERT INTO `#__js_res_field_telephone` VALUES (134,'Mayotte','YT','MYT','262');
INSERT INTO `#__js_res_field_telephone` VALUES (135,'Mexico','MX','MEX','52');
INSERT INTO `#__js_res_field_telephone` VALUES (136,'Micronesia','FM','FSM','691');
INSERT INTO `#__js_res_field_telephone` VALUES (137,'Moldova','MD','MDA','373');
INSERT INTO `#__js_res_field_telephone` VALUES (138,'Monaco','MC','MCO','377');
INSERT INTO `#__js_res_field_telephone` VALUES (139,'Mongolia','MN','MNG','976');
INSERT INTO `#__js_res_field_telephone` VALUES (140,'Montenegro','ME','MNE','382');
INSERT INTO `#__js_res_field_telephone` VALUES (141,'Montserrat','MS','MSR','1-664');
INSERT INTO `#__js_res_field_telephone` VALUES (142,'Morocco','MA','MAR','212');
INSERT INTO `#__js_res_field_telephone` VALUES (143,'Mozambique','MZ','MOZ','258');
INSERT INTO `#__js_res_field_telephone` VALUES (144,'Namibia','NA','NAM','264');
INSERT INTO `#__js_res_field_telephone` VALUES (145,'Nauru','NR','NRU','674');
INSERT INTO `#__js_res_field_telephone` VALUES (146,'Nepal','NP','NPL','977');
INSERT INTO `#__js_res_field_telephone` VALUES (147,'Netherlands','NL','NLD','31');
INSERT INTO `#__js_res_field_telephone` VALUES (148,'Netherlands Antilles','AN','ANT','599');
INSERT INTO `#__js_res_field_telephone` VALUES (149,'New Caledonia','NC','NCL','687');
INSERT INTO `#__js_res_field_telephone` VALUES (150,'New Zealand','NZ','NZL','64');
INSERT INTO `#__js_res_field_telephone` VALUES (151,'Nicaragua','NI','NIC','505');
INSERT INTO `#__js_res_field_telephone` VALUES (152,'Niger','NE','NER','227');
INSERT INTO `#__js_res_field_telephone` VALUES (153,'Nigeria','NG','NGA','234');
INSERT INTO `#__js_res_field_telephone` VALUES (154,'Niue','NU','NIU','683');
INSERT INTO `#__js_res_field_telephone` VALUES (155,'Norfolk Island','','','672');
INSERT INTO `#__js_res_field_telephone` VALUES (156,'North Korea','KP','PRK','850');
INSERT INTO `#__js_res_field_telephone` VALUES (157,'Northern Mariana Islands','MP','MNP','1-670');
INSERT INTO `#__js_res_field_telephone` VALUES (158,'Norway','NO','NOR','47');
INSERT INTO `#__js_res_field_telephone` VALUES (159,'Oman','OM','OMN','968');
INSERT INTO `#__js_res_field_telephone` VALUES (160,'Pakistan','PK','PAK','92');
INSERT INTO `#__js_res_field_telephone` VALUES (161,'Palau','PW','PLW','680');
INSERT INTO `#__js_res_field_telephone` VALUES (162,'Panama','PA','PAN','507');
INSERT INTO `#__js_res_field_telephone` VALUES (163,'Papua New Guinea','PG','PNG','675');
INSERT INTO `#__js_res_field_telephone` VALUES (164,'Paraguay','PY','PRY','595');
INSERT INTO `#__js_res_field_telephone` VALUES (165,'Peru','PE','PER','51');
INSERT INTO `#__js_res_field_telephone` VALUES (166,'Philippines','PH','PHL','63');
INSERT INTO `#__js_res_field_telephone` VALUES (167,'Pitcairn Islands','PN','PCN','870');
INSERT INTO `#__js_res_field_telephone` VALUES (168,'Poland','PL','POL','48');
INSERT INTO `#__js_res_field_telephone` VALUES (169,'Portugal','PT','PRT','351');
INSERT INTO `#__js_res_field_telephone` VALUES (170,'Puerto Rico','PR','PRI','1');
INSERT INTO `#__js_res_field_telephone` VALUES (171,'Qatar','QA','QAT','974');
INSERT INTO `#__js_res_field_telephone` VALUES (172,'Republic of the Congo','CG','COG','242');
INSERT INTO `#__js_res_field_telephone` VALUES (173,'Romania','RO','ROU','40');
INSERT INTO `#__js_res_field_telephone` VALUES (174,'Russia','RU','RUS','7');
INSERT INTO `#__js_res_field_telephone` VALUES (175,'Rwanda','RW','RWA','250');
INSERT INTO `#__js_res_field_telephone` VALUES (176,'Saint Barthelemy','BL','BLM','590');
INSERT INTO `#__js_res_field_telephone` VALUES (177,'Saint Helena','SH','SHN','290');
INSERT INTO `#__js_res_field_telephone` VALUES (178,'Saint Kitts and Nevis','KN','KNA','1-869');
INSERT INTO `#__js_res_field_telephone` VALUES (179,'Saint Lucia','LC','LCA','1-758');
INSERT INTO `#__js_res_field_telephone` VALUES (180,'Saint Martin','MF','MAF','1-599');
INSERT INTO `#__js_res_field_telephone` VALUES (181,'Saint Pierre and Miquelon','PM','SPM','508');
INSERT INTO `#__js_res_field_telephone` VALUES (182,'Saint Vincent and the Grenadines','VC','VCT','1-784');
INSERT INTO `#__js_res_field_telephone` VALUES (183,'Samoa','WS','WSM','685');
INSERT INTO `#__js_res_field_telephone` VALUES (184,'San Marino','SM','SMR','378');
INSERT INTO `#__js_res_field_telephone` VALUES (185,'Sao Tome and Principe','ST','STP','239');
INSERT INTO `#__js_res_field_telephone` VALUES (186,'Saudi Arabia','SA','SAU','966');
INSERT INTO `#__js_res_field_telephone` VALUES (187,'Senegal','SN','SEN','221');
INSERT INTO `#__js_res_field_telephone` VALUES (188,'Serbia','RS','SRB','381');
INSERT INTO `#__js_res_field_telephone` VALUES (189,'Seychelles','SC','SYC','248');
INSERT INTO `#__js_res_field_telephone` VALUES (190,'Sierra Leone','SL','SLE','232');
INSERT INTO `#__js_res_field_telephone` VALUES (191,'Singapore','SG','SGP','65');
INSERT INTO `#__js_res_field_telephone` VALUES (192,'Slovakia','SK','SVK','421');
INSERT INTO `#__js_res_field_telephone` VALUES (193,'Slovenia','SI','SVN','386');
INSERT INTO `#__js_res_field_telephone` VALUES (194,'Solomon Islands','SB','SLB','677');
INSERT INTO `#__js_res_field_telephone` VALUES (195,'Somalia','SO','SOM','252');
INSERT INTO `#__js_res_field_telephone` VALUES (196,'South Africa','ZA','ZAF','27');
INSERT INTO `#__js_res_field_telephone` VALUES (197,'South Korea','KR','KOR','82');
INSERT INTO `#__js_res_field_telephone` VALUES (198,'Spain','ES','ESP','34');
INSERT INTO `#__js_res_field_telephone` VALUES (199,'Sri Lanka','LK','LKA','94');
INSERT INTO `#__js_res_field_telephone` VALUES (200,'Sudan','SD','SDN','249');
INSERT INTO `#__js_res_field_telephone` VALUES (201,'Suriname','SR','SUR','597');
INSERT INTO `#__js_res_field_telephone` VALUES (202,'Svalbard','SJ','SJM','');
INSERT INTO `#__js_res_field_telephone` VALUES (203,'Swaziland','SZ','SWZ','268');
INSERT INTO `#__js_res_field_telephone` VALUES (204,'Sweden','SE','SWE','46');
INSERT INTO `#__js_res_field_telephone` VALUES (205,'Switzerland','CH','CHE','41');
INSERT INTO `#__js_res_field_telephone` VALUES (206,'Syria','SY','SYR','963');
INSERT INTO `#__js_res_field_telephone` VALUES (207,'Taiwan','TW','TWN','886');
INSERT INTO `#__js_res_field_telephone` VALUES (208,'Tajikistan','TJ','TJK','992');
INSERT INTO `#__js_res_field_telephone` VALUES (209,'Tanzania','TZ','TZA','255');
INSERT INTO `#__js_res_field_telephone` VALUES (210,'Thailand','TH','THA','66');
INSERT INTO `#__js_res_field_telephone` VALUES (211,'Timor-Leste','TL','TLS','670');
INSERT INTO `#__js_res_field_telephone` VALUES (212,'Togo','TG','TGO','228');
INSERT INTO `#__js_res_field_telephone` VALUES (213,'Tokelau','TK','TKL','690');
INSERT INTO `#__js_res_field_telephone` VALUES (214,'Tonga','TO','TON','676');
INSERT INTO `#__js_res_field_telephone` VALUES (215,'Trinidad and Tobago','TT','TTO','1-868');
INSERT INTO `#__js_res_field_telephone` VALUES (216,'Tunisia','TN','TUN','216');
INSERT INTO `#__js_res_field_telephone` VALUES (217,'Turkey','TR','TUR','90');
INSERT INTO `#__js_res_field_telephone` VALUES (218,'Turkmenistan','TM','TKM','993');
INSERT INTO `#__js_res_field_telephone` VALUES (219,'Turks and Caicos Islands','TC','TCA','1-649');
INSERT INTO `#__js_res_field_telephone` VALUES (220,'Tuvalu','TV','TUV','688');
INSERT INTO `#__js_res_field_telephone` VALUES (221,'Uganda','UG','UGA','256');
INSERT INTO `#__js_res_field_telephone` VALUES (222,'Ukraine','UA','UKR','380');
INSERT INTO `#__js_res_field_telephone` VALUES (223,'United Arab Emirates','AE','ARE','971');
INSERT INTO `#__js_res_field_telephone` VALUES (224,'United Kingdom','GB','GBR','44');
INSERT INTO `#__js_res_field_telephone` VALUES (225,'United States','US','USA','1');
INSERT INTO `#__js_res_field_telephone` VALUES (226,'Uruguay','UY','URY','598');
INSERT INTO `#__js_res_field_telephone` VALUES (227,'US Virgin Islands','VI','VIR','1-340');
INSERT INTO `#__js_res_field_telephone` VALUES (228,'Uzbekistan','UZ','UZB','998');
INSERT INTO `#__js_res_field_telephone` VALUES (229,'Vanuatu','VU','VUT','678');
INSERT INTO `#__js_res_field_telephone` VALUES (230,'Venezuela','VE','VEN','58');
INSERT INTO `#__js_res_field_telephone` VALUES (231,'Vietnam','VN','VNM','84');
INSERT INTO `#__js_res_field_telephone` VALUES (232,'Wallis and Futuna','WF','WLF','681');
INSERT INTO `#__js_res_field_telephone` VALUES (233,'West Bank','','','970');
INSERT INTO `#__js_res_field_telephone` VALUES (234,'Western Sahara','EH','ESH','');
INSERT INTO `#__js_res_field_telephone` VALUES (235,'Yemen','YE','YEM','967');
INSERT INTO `#__js_res_field_telephone` VALUES (236,'Zambia','ZM','ZMB','260');
INSERT INTO `#__js_res_field_telephone` VALUES (237,'Zimbabwe','ZW','ZWE','263');