<?php
/**
 * Joomcck by joomcoder
 * a component for Joomla! 1.7 - 2.5 CMS (http://www.joomla.org)
 * Author Website: https://www.joomcoder.com/
 * @copyright Copyright (C) 2012 joomcoder (https://www.joomcoder.com). All rights reserved.
 * @license   GNU/GPL http://www.gnu.org/copyleft/gpl.html
 */

namespace Joomcck\Html\Helpers;

use Joomla\CMS\Language\Text;

defined('_JEXEC') or die();

Class Dropdown extends \Joomla\CMS\HTML\Helpers\Dropdown{

	public static function addCustomItem($label, $link = 'javascript:void(0)', $linkAttributes = '', $className = '', $ajaxLoad = false, $jsCallBackFunc = null)
	{

		$linkAttributes = "class='dropdown-item' ".$linkAttributes;

		// add icon automatically
		switch ($label){
			case Text::_('JACTION_EDIT'):
				$label = "<i class='fas fa-edit'></i> ".$label;
				break;
			case Text::_('JTOOLBAR_PUBLISH'):
				$label = "<i class='fas fa-check'></i> ".$label;
				break;
			case Text::_('JTOOLBAR_UNPUBLISH'):
				$label = "<i class='fas fa-times text-muted'></i> ".$label;
				break;
			case Text::_('JTOOLBAR_CHECKIN'):
				$label = "<i class='fas fa-unlock'></i> ".$label;
				break;
		}



		parent::addCustomItem($label, $link, $linkAttributes, $className, $ajaxLoad, $jsCallBackFunc); // TODO: Change the autogenerated stub
	}



	public static function edit($id, $prefix = '', $customLink = '')
	{
		parent::edit($id, $prefix, $customLink); // TODO: Change the autogenerated stub
	}


}